# frozen_string_literal: true
require 'relax_admin/engine'
require 'cancancan'
require 'kaminari'
require 'groupdate'
require 'ruby_identicon'
require 'bcrypt'
require 'chartkick'
require 'chart-js-rails'
require 'highcharts-rails'
require 'selectize-rails'
require 'font-awesome-rails'
require 'bootstrap'
require 'cocoon'
require 'datetime_picker_rails'
require 'jquery-rails'
require 'bootstrap-datepicker-rails'
require 'jquery-minicolors-rails'
require 'momentjs-rails'
require 'sass-rails'
require 'tether-rails'
require 'sweetalert-rails'
require 'http_accept_language'
require 'batch_translation'

module RelaxAdmin
end
